# `cat bashrc >> ~/.bashrc`
#
# with `crontab -e`, add:
# @reboot sh -c 'sleep 30 && nohup python3 /home/philip/PhilNav/server_raspberrypi/main.py &'

if test "$(ps aux | grep -i '[P]hilNav')"; then
  echo
  echo "PhilNav is running:"
  ps aux | grep -i '[P]hilNav'
fi

echo
echo "Stop PhilNav with:"
echo "pkill -f PhilNav"

echo
echo "Run PhilNav with (optionally with '--preview' to see camera view):"
echo "nohup python3 /home/philip/PhilNav/server_raspberrypi/main.py &"
echo
